spring:
  application:
    name: feign
  cloud:
    openfeign:
      client:
        config:
          lotrClient:
            url: http://localhost:8080/api/lotr
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
#            errorDecoder: com.example.SimpleErrorDecoder
#            retryer: com.example.SimpleRetryer
#            defaultQueryParameters:
#              query: queryValue
#            defaultRequestHeaders:
#              header: headerValue
#            requestInterceptors:
#              - com.example.FooRequestInterceptor
#              - com.example.BarRequestInterceptor
#            responseInterceptor: com.example.BazResponseInterceptor
#            dismiss404: false
#            encoder: com.example.SimpleEncoder
#            decoder: com.example.SimpleDecoder
#            contract: com.example.SimpleContract
#            capabilities:
#              - com.example.FooCapability
#              - com.example.BarCapability
#            queryMapEncoder: com.example.SimpleQueryMapEncoder
            micrometer.enabled: false
